# fly -t concourse set-pipeline -p docker-images -c build-docker-images.yaml -l config.yaml

resource_types:
- name: docker-manifest
  type: docker-image
  source:
    repository: mbialon/concourse-docker-manifest-resource

resources:
- name: image-manifest
  type: docker-manifest
  source:
    repository: mbialon/image
    username: condabot
    password: ((dockerhub_password))

- name: docker-images
  type: git
  source:
    uri: https://((recipe-repo-access-token))@github.com/ContinuumIO/docker-images.git
    branch: master

- name: docker-image-miniconda
  type: docker-image
  source:
    password: ((dockerhub_password))
    repository: continuumio/miniconda
    username: condabot

- name: docker-image-miniconda2
  type: docker-image
  source:
    password: ((dockerhub_password))
    repository: continuumio/miniconda2
    username: condabot

- name: docker-image-miniconda3
  type: docker-image
  source:
    password: ((dockerhub_password))
    repository: continuumio/miniconda3
    username: condabot

- name: docker-image-anaconda
  type: docker-image
  source:
    password: ((dockerhub_password))
    repository: continuumio/anaconda
    username: condabot

- name: docker-image-anaconda2
  type: docker-image
  source:
    password: ((dockerhub_password))
    repository: continuumio/anaconda2
    username: condabot

- name: docker-image-anaconda3
  type: docker-image
  source:
    password: ((dockerhub_password))
    repository: continuumio/anaconda3
    username: condabot

- name: anaconda3-amd64-debian
  type: docker-image
  source:
    password: ((dockerhub_password))
    repository: continuumio/anaconda3
    username: condabot
    tag: 2021.05

- name: anaconda3-amd64-alpine
  type: docker-image
  source:
    password: ((dockerhub_password))
    repository: continuumio/anaconda3
    username: condabot
    tag: 2021.05-alpine

- name: anaconda3-arm64-amazonlinux
  type: docker-image
  source:
    password: ((dockerhub_password))
    repository: continuumio/anaconda3
    username: condabot
    tag: 2021.05-amazonlinux

jobs:
  - name: build_miniconda
    plan:
      - get: docker-images
      - put: docker-image-miniconda
        params:
          build: docker-images/miniconda/alpine
          tag_file: docker-images/ci/miniconda-alpine
      - put: docker-image-miniconda
        params:
          build: docker-images/miniconda/debian
          tag_as_latest: true
          tag_file: docker-images/ci/miniconda-debian
  - name: build_miniconda2
    plan:
      - get: docker-images
      - put: docker-image-miniconda2
        params:
          build: docker-images/miniconda/alpine
          tag_file: docker-images/ci/miniconda-alpine
      - put: docker-image-miniconda2
        params:
          build: docker-images/miniconda/debian
          tag_as_latest: true
          tag_file: docker-images/ci/miniconda-debian
  - name: build_miniconda3
    plan:
      - get: docker-images
      - put: docker-image-miniconda3
        params:
          build: docker-images/miniconda3/alpine
          tag_file: docker-images/ci/miniconda-alpine
      - put: docker-image-miniconda3
        params:
          build: docker-images/miniconda3/debian
          tag_as_latest: true
          tag_file: docker-images/ci/miniconda-debian

  - name: build_anaconda
    plan:
      - get: docker-images
      - put: docker-image-anaconda
        params:
          build: docker-images/anaconda/alpine
          tag_file: docker-images/ci/anaconda-alpine
      - put: docker-image-anaconda
        params:
          build: docker-images/anaconda/debian
          tag_as_latest: true
          tag_file: docker-images/ci/anaconda-debian
  - name: build_anaconda2
    plan:
      - get: docker-images
      - put: docker-image-anaconda2
        params:
          build: docker-images/anaconda/alpine
          tag_file: docker-images/ci/anaconda-alpine
      - put: docker-image-anaconda2
        params:
          build: docker-images/anaconda/debian
          tag_as_latest: true
          tag_file: docker-images/ci/anaconda-debian
  - name: build_anaconda3
    plan:
      - get: docker-images
      - put: docker-image-anaconda3
        params:
          build: docker-images/anaconda3/alpine
          tag_file: docker-images/ci/anaconda-alpine
      - put: docker-image-anaconda3
        params:
          build: docker-images/anaconda3/debian
          tag_as_latest: true
          tag_file: docker-images/ci/anaconda-debian
      - put: docker-image-anaconda3
        params:
          build: docker-images/anaconda3/amazonlinux
          tag_file: docker-images/ci/anaconda-amazonlinux
  - name: build manifest from images
    plan:
      - get: anaconda3-amd64-debian
      - get: anaconda3-amd64-alpine
      - get: anaconda3-arm64-amazonlinux
      - put: build manifest
        params:
          tag_file: docker-images/ci/anaconda-debian
          manifests:
            - arch: amd64
              os: linux
              digest_file: anaconda3-amd64-debian/digest
            - arch: amd64
              os: linux
              digest_file: anaconda3-amd64-alpine/digest
            - arch: arm64
              os: linux
              digest_file: anaconda3-amazonlinux/digest
