name: Build Anaconda3 Debian Image
on:
  push:
    paths:
      - 'anaconda3/debian/Dockerfile'
      - '.github/workflows/anaconda_debian_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/debian/Dockerfile'
      - '.github/workflows/anaconda_debian_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
        with:
          version: latest
          driver-opts: network=host

      - name: Build anaconda3/debian
        uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
        with:
          context: ./anaconda3/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/debian/Dockerfile
          tags: continuumio/anaconda3:latest
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: ${{ github.ref == 'refs/heads/master' }}
