name: Lint with Hadolint
on:
  pull_request:
    paths:
      - '**/Dockerfile'
      - '.github/workflows/lint.yml'
  push:
    paths:
      - '**/Dockerfile'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Lint
        run: |
          echo "::add-matcher::.github/hadolint-matcher.json"
          make lint-docker
          echo "::remove-matcher owner=hadolint::"
